version: "3.8"

services:
  backend:
    image: venkteshsha/micro-backend
    container_name: backend_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=your-db-host
      - DB_USER=username
      - DB_PASS=password

  frontend:
    image: venkteshsha/micro-frontend
    container_name: frontend_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
